let names = [
    'Khyati Contractor',
    'Kevin Moonen',
    'Malvin Luk',
    'Francisco Gamez',
    'JISHAN DHUKA',
    'Eric Anh-Hao Nguyen',
    'Thomas Radcliffe Reckling V',
    'Palmi',
    'Gwen MacIver',
    'Rob Gonzalez-Pita',
    'Alexandra Ballester Rovira',
    'Roberto Gonzalez-Pita',
    'Tristan Chester',
    'James Snell',
    'Daniel Peaslee',
    'Fernando Longoria',
    'Darren Napier',
    'Aaron Devine',
    'Parvana Aliyeva',
    'Hannah Buckland',
    'robert karow',
    'Judy Chiang',
    'Kaleb Lee',
    'Ian Hwang',
    'Andrew Shin',
    'Judy Chiang',
    'Jesse Gonzalez',
    'Eddie Huang',
    'Akbar Shakoor',
    'Eivin Kent Adlawan',
    'Phillip Headen',
    'Simply Grateful',
    'Lachelle Fryett',
    'wayne davis',
    'Connor Philip Horn',
    'Andrew Wilson',
    'Max Einhorn',
    'Jessica Yu',
    'Ryan Dill',
    'Ryan Zhong',
    'Shawn Bryant',
    'Amanda Kylee Warshaw',
    'Peeja Khorashadi',
    'HALISAI SAIPULAMU',
    'Phyu (Elisa) Swan',
    'Rahim Laiwalla',
    'Peeja Khorashadi',
    'Harrison Obeid',
    'Ardalan Memar',
    'Jonathan Dobisch',
    'Saarim Zafar',
    'Richard lovata',
    'Richard T.lovata',
    'Alexander Cravalho',
    'Dennis Kim',
    'Matthew Beckerleg',
    'Richard lovata',
    'Hai Huynh',
    'Joey Liu',
    'Evan Schweitzer',
    'scott sarver',
    'Bradley Woolf',
    'Alexander Bonwit',
    'Amiad Davis',
    'Travis Russell',
    'Christopher Stangle',
    'Spencer Michael Davis',
    'Casey Hill-Dixon',
    'John Coffey',
    'Amer Shabou',
    'Lachelle Fryett',
    'Casey Hill-Dixon',
    'Jessica Zhen',
    'Shain Carrasco',
    'Ryan Dill',
    'Richard Cole',
    'Unnur Sigurgeirsdottir',
    'sunitha kaushik',
    'Jesse Gonzalez',
    'HALISAI SAIPULAMU',
    'Eivin Kent Adlawan',
    'James Snell',
]

let emails = [
    'khyati21136',
    '1sj2r6s51e74',
    'malvin.luk',
    'digicisco',
    'jishandhuka90',
    'enguyen21',
    'thomastx12',
    'palmimoller',
    'endolyn.maciver',
    'gonzalrm',
    'alexandramballester',
    'gonzalrm',
    'tristanlchester',
    'danielpeaslee',
    'fernandolongoria',
    'dnaps5',
    'a.f.devine',
    'peroinitworld',
    'hannahtbuckland',
    'karowrobert',
    'jiyc1119',
    'Kaleblee90',
    'meen813',
    'andyrpg',
    'jiyc1119',
    'jesseg2.jg',
    'Eddiehuang97',
    'Shakoor54',
    'eadlawa2',
    'pheaden15',
    'codeschool-sg-hackreactor',
    'lachellefryett',
    'therepoman',
    'connorphiliphorn',
    'andy5x5',
    'maxeinhorn',
    'yujessica',
    'ryanandersondill',
    'ryzhong92',
    'shawnbryant7',
    'kylee.warshaw',
    'khorashadi.peeja',
    'halisasaipulla',
    'elisaswan94',
    'rahim.laiwalla',
    'khorashadi.peeja',
    'harrison.obeid',
    'ardalanmemar',
    'jonnydobisch',
    'saarim.mzafar',
    'Rlovata',
    'rlovata',
    'a.d.cravalho',
    'dekim2324',
    'Matthew.Beckerleg',
    'Rlovata',
    'hihaileapyear',
    'joeyliu224',
    'Eschwei2',
    'scott.sarver',
    'bradleymwoolf',
    'alexbonwit,miaddvs',
    'traviserussell',
    'christopherstangle',
    'spencermdavis',
    'jhilldixon',
    'John.j.coffey12',
    'amershabou',
    'lachellefryett',
    'cjhilldixon',
    'jessicazhen8',
    'shaincarrasco',
    'ryanandersondill',
    'richard.af.cole',
    'unnur.sigurgeirsdottir',
    'sunitha.kaushik',
    'jesseg2.jg',
    'halisasaipulla',
    'eadlawa2',
    'Vulpes3.1415',
]

const workSpace = []
for(let email of emails) {
    workSpace.push({name: email})
}

module.exports = workSpace;